speedrun-war/src/main/java/me/sendow/speedrun/model/AbstractModelBase.java
package me.sendow.speedrun.model;

public abstract class AbstractModelBase<T> {

    public abstract T toEntity();

}

speedrun-war/src/main/java/me/sendow/speedrun/EditCategoryBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.Category;
import me.sendow.speedrun.entity.Game;
import me.sendow.speedrun.model.CategoryModel;
import me.sendow.speedrun.service.CategoryService;
import me.sendow.speedrun.service.GameService;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;

@Named
@SessionScoped
public class EditCategoryBean implements Serializable {

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient GameService gameService;

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient CategoryService categoryService;

    private Long id;
    private CategoryModel model;

    public String init(long categoryId) {
        final Category category = categoryService.findById(categoryId);
        id = category.getId();
        model = new CategoryModel();
        model.setName(category.getName());
        model.setRules(category.getRules());
        return "/category/edit?faces-redirect=true";
    }

    public String edit() {
        final Category category = categoryService.update(id, model.getName(), model.getRules());
        try {
            return String.format("/game?gameId=%d&categoryId=%d&faces-redirect=true", category.getGame().getId(), category.getId());
        } finally {
            id = null;
            model = null;
        }
    }

    public String delete() {
        final Game game = gameService.findByCategory(id);
        categoryService.delete(id);
        try {
            return String.format("/game?gameId=%d&faces-redirect=true", game.getId());
        } finally {
            id = null;
            model = null;
        }
    }

    public CategoryModel getModel() {
        return model;
    }

}

speedrun-war/src/main/java/me/sendow/speedrun/EditEntryBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.Category;
import me.sendow.speedrun.entity.Entry;
import me.sendow.speedrun.model.EntryModel;
import me.sendow.speedrun.service.CategoryService;
import me.sendow.speedrun.service.EntryService;

import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;

@Named
@SessionScoped
public class EditEntryBean implements Serializable {

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient CategoryService categoryService;

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient EntryService entryService;

    private EntryModel model;
    private Category category;

    public String init(long categoryId) {
        this.model = new EntryModel();
        this.category = categoryService.findById(categoryId);
        final String username = FacesContext.getCurrentInstance().getExternalContext().getRemoteUser();
        final Entry entry = entryService.findByUsernameAndCategory(categoryId, username);
        if (entry != null) {
            model.setComputedRunTime(entry.getRunTime());
            model.setVideoUrl(entry.getVideoUrl());
            model.setComment(entry.getComment());
        }
        return "/entry/edit?faces-redirect=true";
    }

    public String createOrEdit() {
        final String username = FacesContext.getCurrentInstance().getExternalContext().getRemoteUser();
        final Entry entry = entryService.findByUsernameAndCategory(category.getId(), username);
        if (entry != null) {
            entryService.update(entry.getId(), model.getComputedRunTime(), model.getVideoUrl(), model.getComment());
        } else {
            model.setUsername(username);
            entryService.createForCategory(model.toEntity(), category.getId());
        }
        try {
            return String.format("/game?gameId=%d&categoryId=%d&faces-redirect=true", category.getGame().getId(), category.getId());
        } finally {
            model = null;
            category = null;
        }
    }

    public EntryModel getModel() {
        return model;
    }
}

speedrun-war/src/main/java/me/sendow/speedrun/EditGameBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.Game;
import me.sendow.speedrun.model.GameModel;
import me.sendow.speedrun.service.GameService;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;

@Named
@SessionScoped
public class EditGameBean implements Serializable {

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient GameService gameService;

    private Long id;
    private GameModel model;

    public String init(long gameId) {
        final Game game = gameService.findById(gameId);
        id = game.getId();
        model = new GameModel();
        model.setTitle(game.getTitle());
        return "/game/edit?faces-redirect=true";
    }

    public String edit() {
        final Game game = gameService.update(id, model.getTitle(), model.getImageData());
        try {
            return String.format("/game?gameId=%d&faces-redirect=true", game.getId());
        } finally {
            id = null;
            model = null;
        }
    }

    public String delete() {
        gameService.delete(id);
        try {
            return "/index?faces-redirect=true";
        } finally {
            id = null;
            model = null;
        }
    }

    public GameModel getModel() {
        return model;
    }

}

speedrun-war/src/main/java/me/sendow/speedrun/EntryBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.Category;
import me.sendow.speedrun.entity.Entry;
import me.sendow.speedrun.service.CategoryService;
import me.sendow.speedrun.service.EntryService;
import me.sendow.speedrun.util.VideoEmbedUtil;

import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.IOException;
import java.io.Serializable;

@Named
@SessionScoped
public class EntryBean implements Serializable {

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient CategoryService categoryService;

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient EntryService entryService;

    private long entryId;
    private Entry entry;
    private long rank;
    private String embedUrl;

    public void init(Long entryId) throws IOException {
        if (entryId == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("/index.jsf");
        } else {
            setEntryId(entryId);
        }
    }

    public long getEntryId() {
        return entryId;
    }

    private void setEntryId(long entryId) {
        this.entryId = entryId;
        entry = entryService.findById(entryId);
        if (entry != null) {
            rank = entryService.getRank(entryId);
            embedUrl = VideoEmbedUtil.getEmbedUrl(entry.getVideoUrl());
        } else {
            rank = 0;
            embedUrl = null;
        }
    }

    public String delete() {
        final Category category = categoryService.findByEntry(entryId);
        entryService.delete(entryId);
        return String.format("/game?gameId=%d&categoryId=%d&faces-redirect=true", category.getGame().getId(), category.getId());
    }

    public Entry getEntry() {
        return entry;
    }

    public long getRank() {
        return rank;
    }

    public String getEmbedUrl() {
        return embedUrl;
    }
}

speedrun-war/src/main/java/me/sendow/speedrun/GameBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.Category;
import me.sendow.speedrun.entity.Entry;
import me.sendow.speedrun.entity.Game;
import me.sendow.speedrun.service.CategoryService;
import me.sendow.speedrun.service.EntryService;
import me.sendow.speedrun.service.GameService;

import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.IOException;
import java.io.Serializable;
import java.util.Collections;
import java.util.List;

@Named
@SessionScoped
public class GameBean implements Serializable {

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient GameService gameService;

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient CategoryService categoryService;

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient EntryService entryService;

    private long gameId;
    private Game game;
    private List<Category> categories;

    private Long categoryId;
    private Category category;
    private List<Entry> entries;

    public void init(Long gameId, Long categoryId) throws IOException {
        if (gameId == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("/index.jsf");
        } else {
            setGameId(gameId);
            if (categoryId != null) {
                setCategoryId(categoryId);
            }
        }
    }

    public long getGameId() {
        return gameId;
    }

    private void setGameId(long gameId) {
        this.gameId = gameId;
        this.game = gameService.findById(gameId);
        this.categoryId = null;
        this.category = null;
        this.entries = null;
        if (game != null) {
            this.categories = categoryService.listForGame(game.getId());
        } else {
            try {
                FacesContext.getCurrentInstance().getExternalContext().redirect("/game/new.jsf");
            } catch (IOException e) {
                throw new RuntimeException("Cannot redirect", e);
            }
        }
    }

    public Game getGame() {
        return game;
    }

    public List<Category> getCategories() {
        return categories;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    private void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
        this.category = categoryService.findById(categoryId);
        if (category != null) {
            this.entries = entryService.listForCategory(categoryId);
        } else {
            this.entries = Collections.emptyList();
        }
    }

    public Category getCategory() {
        return category;
    }

    public List<Entry> getEntries() {
        return entries;
    }

}

speedrun-war/src/main/java/me/sendow/speedrun/IndexBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.Game;
import me.sendow.speedrun.service.GameService;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

@Named
@ApplicationScoped
public class IndexBean {

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient GameService gameService;

    public List<Game> getGameList() {
        return gameService.listAll();
    }

}

speedrun-war/src/main/java/me/sendow/speedrun/LoginBean.java
package me.sendow.speedrun;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

@Named
@RequestScoped
public class LoginBean {

    @Inject
    private HttpServletRequest request;

    private String username;
    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public boolean isLoggedIn() {
        return request.isUserInRole("**");
    }

    public boolean isAdmin() {
        return request.isUserInRole("admin");
    }

    public String login() {
        if (request.getAuthType() != null) {
            return "/index?faces-redirect=true";
        }
        try {
            request.login(username, password);
            return "/index?faces-redirect=true";
        } catch (ServletException e) {
            e.printStackTrace();
            return "/login?faces-redirect=true&loginError=1";
        }
    }

    public String logout() throws ServletException {
        request.logout();
        return "/index?faces-redirect=true";
    }

}

speedrun-war/src/main/java/me/sendow/speedrun/NewCategoryBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.Category;
import me.sendow.speedrun.entity.Game;
import me.sendow.speedrun.model.CategoryModel;
import me.sendow.speedrun.service.CategoryService;
import me.sendow.speedrun.service.GameService;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;

@Named
@SessionScoped
public class NewCategoryBean implements Serializable {

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient GameService gameService;

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient CategoryService categoryService;

    private CategoryModel model;
    private Game game;

    public String init(long gameId) {
        this.model = new CategoryModel();
        this.game = gameService.findById(gameId);
        return "/category/new?faces-redirect=true";
    }

    public String create() {
        final Category category = model.toEntity();
        categoryService.createForGame(category, game.getId());
        try {
            return String.format("/game?gameId=%d&categoryId=%d&faces-redirect=true", game.getId(), category.getId());
        } finally {
            game = null;
            model = null;
        }
    }

    public CategoryModel getModel() {
        return model;
    }

}

speedrun-war/src/main/java/me/sendow/speedrun/NewGameBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.Game;
import me.sendow.speedrun.model.GameModel;
import me.sendow.speedrun.service.GameService;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;

@Named
@SessionScoped
public class NewGameBean implements Serializable {

    @Inject
    @SuppressWarnings("CdiUnproxyableBeanTypesInspection")
    private transient GameService gameService;

    private GameModel model = new GameModel();

    public void init() {
        model = new GameModel();
    }

    public String create() {
        final Game game = gameService.create(model.toEntity());
        try {
            return String.format("/game?gameId=%d&faces-redirect=true", game.getId());
        } finally {
            model = null;
        }
    }

    public GameModel getModel() {
        return model;
    }

}

speedrun-war/src/main/java/me/sendow/speedrun/RegisterBean.java
package me.sendow.speedrun;

import me.sendow.speedrun.entity.User;
import me.sendow.speedrun.service.UserService;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Named
@RequestScoped
public class RegisterBean {

    @Inject
    private UserService userService;

    @Inject
    private HttpServletRequest request;

    @NotNull
    @Size(min = 1, max = 255)
    private String username;
    @NotNull
    @Size(min = 1, max = 1024)
    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String register() {
        if (request.getAuthType() != null) {
            return "/index?faces-redirect=true";
        }
        final User newUser = userService.create(username, password);
        if (newUser != null) {
            return "/index?faces-redirect=true";
        } else {
            final FacesContext facesContext = FacesContext.getCurrentInstance();
            ((UIInput) facesContext.getViewRoot().findComponent("registerForm:username")).setValid(false);
            final FacesMessage errorMessage = new FacesMessage("username already in use: " + username);
            errorMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
            facesContext.addMessage("registerForm:username", errorMessage);
            facesContext.validationFailed();
            return null;
        }

    }

}

speedrun-war/src/main/webapp/error.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<ui:composition template="/WEB-INF/template.xhtml">
    <ui:define name="content">
        <h2>Login</h2>
        <form action="j_security_check" method="post">
            <div class="form-group has-error">
                <label for="username">Username</label>
                <input id="username" type="text" name="j_username" placeholder="Username" class="form-control"/>
            </div>
            <div class="form-group has-error">
                <label for="password">Password</label>
                <input id="password" type="password" name="j_password" placeholder="Password" class="form-control"/>
            </div>
            <button class="btn btn-primary">Login</button>
        </form>
    </ui:define>
</ui:composition>

</html>

speedrun-war/src/main/webapp/game.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<ui:composition template="/WEB-INF/template.xhtml">
    <ui:define name="metadata">
        <f:metadata>
            <f:viewAction action="#{gameBean.init(param.gameId, param.categoryId)}"/>
        </f:metadata>
    </ui:define>
    <ui:define name="content">
        <h:form>
            <div class="row">
                <div class="col-md-7">
                    <h2>#{gameBean.game.title}</h2>
                </div>
                <div class="col-md-5">
                    <h:panelGroup layout="block" styleClass="btn-group pull-right" rendered="#{loginBean.loggedIn}">
                        <h:commandButton action="#{editGameBean.init(gameBean.gameId)}" value="Edit Game"
                                       styleClass="btn btn-warning" rendered="#{loginBean.admin}"/>
                        <h:commandButton action="#{newCategoryBean.init(gameBean.gameId)}" value="New Category"
                                       styleClass="btn btn-primary"/>
                        <h:commandButton action="#{editCategoryBean.init(gameBean.categoryId)}" value="Edit Category"
                                       styleClass="btn btn-warning"
                                       rendered="#{loginBean.admin and gameBean.categoryId ne null}"/>
                        <h:commandButton action="#{editEntryBean.init(gameBean.categoryId)}" value="Edit Entry"
                                       styleClass="btn btn-success" rendered="#{gameBean.categoryId ne null}"/>
                    </h:panelGroup>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <h:graphicImage value="/game/image/#{gameBean.gameId}" styleClass="img-responsive center-block"/>
                </div>
                <div class="col-md-8">
                    <ui:fragment rendered="#{not empty gameBean.categories}">
                        <ul class="nav nav-tabs">
                            <ui:repeat value="#{gameBean.categories}" var="category">
                                <li class="#{gameBean.categoryId==category.id?'active':''}">
                                    <h:link outcome="/game" value="#{category.name}">
                                        <f:param name="gameId" value="#{gameBean.gameId}"/>
                                        <f:param name="categoryId" value="#{category.id}"/>
                                    </h:link>
                                </li>
                            </ui:repeat>
                        </ul>
                        <ui:fragment rendered="#{gameBean.categoryId ne null}">
                            <table class="table table-condensed #{not empty gameBean.entries?'table-hover':''}">
                                <colgroup>
                                    <col class="css-col-rank"/>
                                    <col class="css-col-player"/>
                                    <col class="css-col-time"/>
                                    <col class="css-col-details"/>
                                </colgroup>
                                <thead>
                                <tr>
                                    <th>Rank</th>
                                    <th>Player</th>
                                    <th>Time</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr jsfc="ui:repeat" value="#{gameBean.entries}" var="entry" varStatus="status">
                                    <td>#{status.index + 1}</td>
                                    <td>#{entry.username}</td>
                                    <td>
                                        <h:outputText value="#{entry.runTime}"
                                                      converter="me.sendow.speedrun.jsf.converter.RunTimeConverter"/>
                                    </td>
                                    <td>
                                        <h:link outcome="/entry/view" value="Details">
                                            <f:param name="entryId" value="#{entry.id}"/>
                                        </h:link><h:outputText value="&#x2002;"/>
                                        <ui:fragment rendered="#{not empty entry.videoUrl}">
                                            <span class="glyphicon glyphicon-film"/>
                                        </ui:fragment>
                                        <ui:fragment rendered="#{not empty entry.comment}">
                                            <span class="glyphicon glyphicon-comment"/>
                                        </ui:fragment>
                                    </td>
                                </tr>
                                <ui:fragment rendered="#{empty gameBean.entries}">
                                    <tr>
                                        <td class="text-center bg-warning" colspan="4">There are no entries.</td>
                                    </tr>
                                </ui:fragment>
                                </tbody>
                            </table>
                            <ui:fragment rendered="#{not empty gameBean.category.rules}">
                                <details class="well well-sm" open="open">
                                    <summary><strong>Rules</strong></summary>
                                    <p class="css-pre">#{gameBean.category.rules}</p>
                                </details>
                            </ui:fragment>
                        </ui:fragment>
                        <h:panelGroup layout="block" styleClass="alert alert-info css-select-category-alert"
                                      rendered="#{gameBean.categoryId eq null}">Please select a category!</h:panelGroup>
                    </ui:fragment>
                    <h:panelGroup layout="block" styleClass="alert alert-warning"
                                  rendered="#{empty gameBean.categories}">There are no categories.</h:panelGroup>
                </div>
            </div>
        </h:form>
    </ui:define>
</ui:composition>

</html>

speedrun-war/src/main/webapp/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<ui:composition template="/WEB-INF/template.xhtml">
    <ui:define name="content">
        <div class="row">
            <div class="col-md-8">
                <h2>Game list</h2>
            </div>
            <div class="col-md-4 clearfix">
                <div class="btn-group pull-right">
                    <h:link outcome="/game/new" value="New Game" styleClass="btn btn-primary"
                            rendered="#{loginBean.loggedIn}"/>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="list-group">
                <ui:repeat value="#{indexBean.gameList}" var="game">
                    <h:link outcome="/game" value="#{game.title}" styleClass="list-group-item">
                        <f:param name="gameId" value="#{game.id}"/>
                    </h:link>
                </ui:repeat>
            </div>
        </div>
    </ui:define>
</ui:composition>

</html>

speedrun-war/src/main/webapp/j_login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<ui:composition template="/WEB-INF/template.xhtml">
    <ui:define name="content">
        <h2>Login</h2>
        <form action="j_security_check" method="post">
            <div class="form-group">
                <label for="username">Username</label>
                <input id="username" type="text" name="j_username" placeholder="Username" class="form-control"/>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input id="password" type="password" name="j_password" placeholder="Password" class="form-control"/>
            </div>
            <button class="btn btn-primary">Login</button>
        </form>
    </ui:define>
</ui:composition>

</html>

speedrun-war/src/main/webapp/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<ui:composition template="/WEB-INF/template.xhtml">
    <ui:define name="content">
        <h2>Login</h2>
        <h:form>
            <div class="form-group">
                <h:outputLabel for="username" value="Username"/>
                <h:inputText id="username" value="#{loginBean.username}" pt:placeholder="Username"
                             styleClass="form-control" pt:autofocus=""/>
            </div>
            <div class="form-group">
                <h:outputLabel for="password" value="Password"/>
                <h:inputSecret id="password" value="#{loginBean.password}" pt:placeholder="Password"
                               styleClass="form-control"/>
            </div>
            <h:commandButton action="#{loginBean.login}" value="Login" styleClass="btn btn-primary"/>
        </h:form>
    </ui:define>
</ui:composition>

</html>

speedrun-war/src/main/webapp/register.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<ui:composition template="/WEB-INF/template.xhtml">
    <ui:define name="content">
        <h2>Register</h2>
        <h:form id="registerForm">
            <h:panelGroup layout="block" styleClass="form-group #{comp.username.valid?'':'has-error'}">
                <h:outputLabel for="username" value="Username"/>
                <h:inputText id="username" value="#{registerBean.username}" binding="#{comp.username}"
                             styleClass="form-control" pt:placeholder="Username" pt:autofocus=""/>
                <h:message for="username" styleClass="help-block"/>
            </h:panelGroup>
            <h:panelGroup layout="block" styleClass="form-group #{comp.password.valid?'':'has-error'}">
                <h:outputLabel for="password" value="Password"/>
                <h:inputSecret id="password" value="#{registerBean.password}" binding="#{comp.password}"
                               styleClass="form-control" pt:placeholder="Password"/>
                <h:message for="password" styleClass="help-block"/>
            </h:panelGroup>
            <h:commandButton action="#{registerBean.register}" value="Login" styleClass="btn btn-primary"/>
        </h:form>
    </ui:define>
</ui:composition>

</html>